import createClient from "openapi-fetch";
import type { paths } from "./schema"; //generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: "https://musicfun.it-incubator.app/api/1.0/",
  headers: {
    "api-key": "5dacb5c0-8de7-4786-90f4-2f8e4513b7e9",
  },
});
